lesson-6/reports/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :lab_reports
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "lab_reports#index"
end

lesson-6/reports/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

lesson-6/reports/app/models/lab_report.rb
class LabReport < ApplicationRecord
  belongs_to :user
  validates :title, presence:true, length: { maximum: 250 }
  validates :description, presence:true, length: { maximum: 500 }
  validates :grade, inclusion: { in: %w[A B C D E FX F] }
end

lesson-6/reports/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :lab_reports, dependent: :destroy
  validates :email, presence: true, length: { maximum: 150 }, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :first_name, length: { maximum: 100 }
  validates :last_name, length: { maximum: 100 }

end

lesson-6/reports/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
end

lesson-6/reports/app/controllers/lab_reports_controller.rb
class LabReportsController < ApplicationController
  before_action :set_lab_report, only: %i[show edit update destroy]

  def index
    @lab_reports = LabReport.all
  end

  def show
  end

  def new
    @lab_report = LabReport.new
  end

  def edit
  end

  def create
    @lab_report = LabReport.new(lab_report_params)

    if @lab_report.save
      redirect_to @lab_report, notice: "Lab report was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @lab_report.update(lab_report_params)
      redirect_to @lab_report, notice: "Lab report was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @lab_report.destroy
    redirect_to lab_reports_url, notice: "Lab report was successfully destroyed."
  end

  private

  def set_lab_report
    @lab_report = LabReport.find(params[:id])
  end

  def lab_report_params
    params.require(:lab_report).permit(:title, :description, :grade, :user_id)
  end
end

lesson-6/reports/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name)
  end
end

lesson-6/reports/app/helpers/application_helper.rb
module ApplicationHelper
end

lesson-6/reports/app/helpers/lab_reports_helper.rb
module LabReportsHelper
end

lesson-6/reports/app/helpers/users_helper.rb
module UsersHelper
end

lesson-6/reports/app/views/lab_reports/_form.html.erb
<%= form_with(model: lab_report) do |form| %>
  <% if lab_report.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lab_report.errors.count, "error") %> prohibited this lab_report from being saved:</h2>

      <ul>
        <% lab_report.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, ->(user) { "#{user.first_name} #{user.last_name}" } %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :grade, style: "display: block" %>
    <%= form.select :grade, %w(A B C D E FX F) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lesson-6/reports/app/views/lab_reports/_lab_report.html.erb
<div id="<%= dom_id lab_report %>">
  <br>

  <p>
    <strong>User:</strong>
    <%= lab_report.user.last_name %> <%= lab_report.user.first_name %> 
  </p>

  <p>
    <strong>Title:</strong>
    <%= lab_report.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= lab_report.description %>
  </p>

  <p>
    <strong>Grade:</strong>
    <%= lab_report.grade %>
  </p>


</div>

lesson-6/reports/app/views/lab_reports/edit.html.erb
<% content_for :title, "Editing lab report" %>

<h1>Editing lab report</h1>

<%= render "form", lab_report: @lab_report %>

<br>

<div>
  <%= link_to "Show this lab report", @lab_report %> |
  <%= link_to "Back to lab reports", lab_reports_path %>
</div>

lesson-6/reports/app/views/lab_reports/index.html.erb
<h1>Lab reports</h1>

<table id="lab_reports">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Grade</th>
      <th>User</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @lab_reports.each do |lab_report| %>
      <tr>
        <td><%= lab_report.title %></td>
        <td><%= lab_report.description %></td>
        <td><%= lab_report.grade %></td>
        <td><%= User.find(lab_report.user_id).attributes.values_at('last_name', 'first_name').join(' ') %></td>
        <td><%= link_to "Show this lab report", lab_report %> </td>
      </tr>      
      <% end %>
  </tbody>


</table> 

<%= link_to "New lab report", new_lab_report_path %>

lesson-6/reports/app/views/lab_reports/new.html.erb
<%= form_with model: @lab_report, url: lab_reports_path do |form| %>
  <%= form.collection_select :user_id, User.all, :id, ->(user) { "#{user.first_name} #{user.last_name}" }, { :include_blank => true } %>
  <%= form.label :title %>
  <%= form.text_field :title %>
  <%= form.label :description %>
  <%= form.text_area :description %>
  <%= form.label :grade %>
  <%= form.select :grade, %w(A B C D E FX F) %>
  <%= form.submit %>
<% end %>

lesson-6/reports/app/views/lab_reports/show.html.erb
<%= render @lab_report %>

<div>
  <%= link_to "Edit this lab report", edit_lab_report_path(@lab_report) %> |
  <%= link_to "Back to lab reports", lab_reports_path %>

  <%= button_to "Destroy this lab report", @lab_report, method: :delete %>
</div>

lesson-6/reports/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Reports" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-900 text-gray-100">
    <header class="bg-gray-800 shadow">
      <% if user_signed_in? %>
        <span><%= current_user.email %></span>
        <div class="inline-block">
          <%= button_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
      <% end %>
    </header>

    <p style="color: green"><%= notice %></p>  
    <p style="color: red"><%= alert %></p>
    <%= yield %>
  </body>
</html>

lesson-6/reports/app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

lesson-6/reports/app/views/users/_user.html.erb
<div id="<%= dom_id user %>">

  <br>
  
  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

</div>

lesson-6/reports/app/views/users/edit.html.erb
<% content_for :title, "Editing user" %>

<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

lesson-6/reports/app/views/users/index.html.erb
<h1>Users</h1>

<table id="Users">
  <thead>
    <tr>
      <th>E-Mail</th>
      <th>Last name</th>
      <th>First name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |users| %>
      <tr>
        <td><%= users.email %></td>
        <td><%= users.last_name %></td>
        <td><%= users.first_name %></td>
        <td><%= link_to "Show this user", users%> </td>
      </tr>      
      <% end %>
  </tbody>


</table> 

<%= link_to "New user", new_user_path %>

lesson-6/reports/app/views/users/new.html.erb
<% content_for :title, "New user" %>

<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

lesson-6/reports/app/views/users/show.html.erb
<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>
  
  <%= button_to "Destroy this user", @user, method: :delete %>
</div>